# Data for Province Chosen

Import packages

In [1]:
import pandas as pd

Set province chosen as variable

In [2]:
province = "CATANDUANES"

Read from CSV file

In [4]:
# read from csv file
df = pd.read_csv(f"filtered_cases/{province}_case_information.csv")
df.head()

,Unnamed: 0,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,19761,C781369,50.0,50 to 54,MALE,2020-05-30,NaN,2020-06-06,NaN,2020-07-07,...,CATANDUANES,SAN MIGUEL,PH052009000,NaN,NaN,RECOVERED,YES,NaN,NaN,Age or Birthdate is Invalid\nCase has Admittin...
1,29313,C636837,47.0,45 to 49,MALE,NaN,NaN,2020-06-22,NaN,2020-07-08,...,CATANDUANES,BAGAMANOC,PH052001000,NaN,NaN,RECOVERED,YES,NaN,NaN,Age or Birthdate is Invalid
2,43311,C951557,1.0,0 to 4,MALE,2020-07-02,2020-07-04,2020-07-06,NaN,2020-07-23,...,CATANDUANES,VIRAC (CAPITAL),PH052011000,NaN,NaN,RECOVERED,NO,2020-06-28,NaN,Age or Birthdate is Invalid
3,45859,C639154,21.0,20 to 24,MALE,2020-06-30,2020-07-05,2020-07-08,NaN,NaN,...,CATANDUANES,CARAMORAN,PH052004000,NaN,NaN,RECOVERED,NO,2020-06-30,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
4,49871,C619176,22.0,20 to 24,FEMALE,2020-07-06,2020-07-07,2020-07-10,NaN,2020-07-23,...,CATANDUANES,VIRAC (CAPITAL),PH052011000,NaN,NaN,RECOVERED,YES,NaN,NO,Age or Birthdate is Invalid

In [9]:
# Number of Cases
print(f"Number of Cases: {df.shape[0]}")
print(f"Number of Deaths: {df[df['RemovalType'] == 'DIED'].shape[0]}")
print(f"Number of Recoveries: {df[df['RemovalType'] == 'RECOVERED'].shape[0]}")

Number of Cases: 4258
Number of Deaths: 40
Number of Recoveries: 4216

# Aggregated Data Analysis

In [5]:
import os

folder = 'aggregated_data/CATANDUANES/'

print(os.listdir(folder))

['BAGAMANOC.csv', 'BARAS.csv', 'BATO.csv', 'CARAMORAN.csv', 'GIGMOTO.csv', 'nan.csv', 'PANDAN.csv', 'PANGANIBAN (PAYO).csv', 'SAN ANDRES (CALOLBON).csv', 'SAN MIGUEL.csv', 'VIGA.csv', 'VIRAC (CAPITAL).csv']

In [7]:
dir = os.listdir(folder)

for file in dir:
    aggdata_ = pd.read_csv(f'{folder}{file}')
    print(aggdata_.head())

         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0
         Date  NewCases  Deaths  Recoveries
0  01/12/2023         1     0.0         0.0
1  01/15/2023         1     0.0         0.0
2  01/27/2023         2     0.0         0.0
3  02/17/2023         2     0.0         0.0
4  03/04/2023         1     0.0         0.0

Based from this summaries, the `aggregated_data` folder pertains to the frequency count of cases per week based on each city/municipality of Catanduanes.

# Filtered Cases Analysis

In [8]:
dir = 'filtered_cases/CATANDUANES_case_information.csv'
df = pd.read_csv(dir)
df.head()

,Unnamed: 0,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,19761,C781369,50.0,50 to 54,MALE,2020-05-30,NaN,2020-06-06,NaN,2020-07-07,...,CATANDUANES,SAN MIGUEL,PH052009000,NaN,NaN,RECOVERED,YES,NaN,NaN,Age or Birthdate is Invalid\r\nCase has Admitt...
1,29313,C636837,47.0,45 to 49,MALE,NaN,NaN,2020-06-22,NaN,2020-07-08,...,CATANDUANES,BAGAMANOC,PH052001000,NaN,NaN,RECOVERED,YES,NaN,NaN,Age or Birthdate is Invalid
2,43311,C951557,1.0,0 to 4,MALE,2020-07-02,2020-07-04,2020-07-06,NaN,2020-07-23,...,CATANDUANES,VIRAC (CAPITAL),PH052011000,NaN,NaN,RECOVERED,NO,2020-06-28,NaN,Age or Birthdate is Invalid
3,45859,C639154,21.0,20 to 24,MALE,2020-06-30,2020-07-05,2020-07-08,NaN,NaN,...,CATANDUANES,CARAMORAN,PH052004000,NaN,NaN,RECOVERED,NO,2020-06-30,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
4,49871,C619176,22.0,20 to 24,FEMALE,2020-07-06,2020-07-07,2020-07-10,NaN,2020-07-23,...,CATANDUANES,VIRAC (CAPITAL),PH052011000,NaN,NaN,RECOVERED,YES,NaN,NO,Age or Birthdate is Invalid

In [9]:
df.shape

(4258, 24)

This one's the original data, filtered with `Province == Catanduanes`.

# Dataset Analysis

In [10]:
dir = 'dataset/DOH COVID 2020-2023 Catanduanes Compiled Dataset.csv'

dataset = pd.read_csv(dir)
dataset.head()

,Unnamed: 0,Age,Sex,DateRepConf,RemovalType,CityMunRes,Pregnanttab,Latitude,Longitude
0,19761,50.0,MALE,2020-06-06,RECOVERED,SAN MIGUEL,NaN,13.640329,124.303109
1,29313,47.0,MALE,2020-06-22,RECOVERED,BAGAMANOC,NaN,13.939637,124.287830
2,43311,1.0,MALE,2020-07-06,RECOVERED,VIRAC (CAPITAL),NaN,13.580359,124.231203
3,45859,21.0,MALE,2020-07-08,RECOVERED,CARAMORAN,NaN,13.983835,124.133872
4,49871,22.0,FEMALE,2020-07-10,RECOVERED,VIRAC (CAPITAL),NO,13.580359,124.231203